services:
  - type: web
    name: agentic-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn api_server:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18